# Data Structures, Functions, Numpy & Pandas

## Section A: Data Structures & Control Structures

In [1]:
# 1. Create a list of 5 integers. 
# Perform and print the result of the following operations: 
        # append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
lst = [10, 20, 30, 40, 50]
# append
lst.append(60)
print(lst)
# insert
lst.insert(2, 70)
print(lst)
# remove
lst.remove(70)
print(lst)
# pop
lst.pop()
print(lst)
# clear
lst.clear()
print(lst)

[10, 20, 30, 40, 50, 60]
[10, 20, 70, 30, 40, 50, 60]
[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 50]
[]

In [3]:
# extend
a = [10, 20]
b = [30, 40]
a.extend(b)
print(a)

[10, 20, 30, 40]

In [4]:
lst1 = [1, 2, 3, 4, 5, 2, 3, 4, 2]
# index
lst1.index(2) # it will give index position of first appearance of 2 

# indexing
print(lst1[0]) # will give value at index position 0
print(lst1[:]) # will give entire list
print(lst1[::-1]) # will give list in reverse order
print(lst1[-1]) # will give value at last position
# Slicing 
print(lst1[0:5]) # fetch value from index 0 to 4
print(lst1[:-1]) # fetch values from first index posiion till index -2

1
[1, 2, 3, 4, 5, 2, 3, 4, 2]
[2, 4, 3, 2, 5, 4, 3, 2, 1]
2
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 2, 3, 4]

In [5]:
# count
lst1.count(2)

3

In [6]:
# sort
lst1.sort()
lst1

[1, 2, 2, 2, 3, 3, 4, 4, 5]

In [7]:
# reverse
lst1.reverse()
lst1

[5, 4, 4, 3, 3, 2, 2, 2, 1]

In [8]:
# 2. Create a tuple that stores 3 student names. 
# Try changing the second name in the tuple. What happens? Explain why.

In [9]:
t = ('Raj', 'Vishal', 'Shreya')
print(t)
t[1] = "Ram"

#This gives "'tuple' object does not support item assignment" as TypeError
# This happens because tuples are immutable, once its created changes cannot be made

('Raj', 'Vishal', 'Shreya')

TypeError: 'tuple' object does not support item assignment

In [10]:
# 3. Create a set of integers with some duplicate values. Print the set and explain the output.

s = {1, 2, 3, 2, 4, 4}
print(s)

# It gives output as {1, 2, 3, 4} because it does not take duplicates. So it only take first appered value in set

{1, 2, 3, 4}

In [11]:
# 4. Create a dictionary with the keys: 'name', 'age', and 'city'. 
# Update the age and add a new key 'email'. Print the final dictionary.

emp_info = {
    'name':'Riya', 'age':24, 'city':'Pune'}
print(emp_info)
emp_info['age'] = 25
emp_info['email']='abc12@gmail.com'
print(emp_info)

{'name': 'Riya', 'age': 24, 'city': 'Pune'}
{'name': 'Riya', 'age': 25, 'city': 'Pune', 'email': 'abc12@gmail.com'}

In [12]:
# 5. Write a script that checks if a person is eligible to vote (age ≥ 18).
# Take age as a variable and print the appropriate message.

age = int(input('Enter your age'))
if age >= 18:
    print('Your eligible to vote')
else:
    print('Your not eligible to vote')

Enter your age 17

Your not eligible to vote

In [13]:
'''6. Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail' '''

marks = int(input('Enter your marks'))
if marks >= 90:                                       # 90 and above: 'A'
    print('You have passed the exam with grade A')
elif (marks >= 75) and (marks <= 89):                 # 75–89: 'B'
    print('You have passed the exam with grade B')
elif marks >= 50 and marks <= 74:                     # 50–74: 'C'
    print('You have passed the exam with grade C')
else:                                                 # Below 50: 'Fail
    print("You have failed the exam")

Enter your marks 50

You have passed the exam with grade C

In [14]:
# 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

number = -4
if number > 0 and number%2==0:
    print("The number is positive and even")
elif number == 0:
    print("The number is Zero")
elif number < 0:
    print("The number is negative")

The number is negative

In [15]:
number = 74
if number > 0 and number%2==0:
    print("The number is positive and even")
elif number == 0:
    print("The number is Zero")
elif number < 0:
    print("The number is negative")

The number is positive and even

In [16]:
number = 0
if number > 0 and number%2==0:
    print("The number is positive and even")
elif number == 0:
    print("The number is Zero")
elif number < 0:
    print("The number is negative")

The number is Zero

## Section B : Numpy

In [17]:
# 8. Create:
'''- A scalar using np.array(5)
   - A 1D array with values 1 to 5
   - A 2D array (2x3) with values from 10 to 60 in steps of 10'''

import numpy as np

scalar = np.array(5)  # A scalar using np.array(5)
print(scalar)

array1 = np.array([1, 2, 3, 4, 5]) # A 1D array with values 1 to 5
print(array1, array1.ndim)

array2 = np.arange(10, 70, 10).reshape(2, 3) # A 2D array (2x3) with values from 10 to 60 in steps of 10
print(array2)

5
[1 2 3 4 5] 1
[[10 20 30]
 [40 50 60]]

In [18]:
# 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

import numpy as np
number = np.random.randint(0, 100, size=(4,4))
array = np.array(number)
array

array([[49, 97, 69, 87],
       [82, 18, 97, 78],
       [75,  1, 94, 48],
       [67, 13,  8, 33]], dtype=int32)

In [19]:
# 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

import numpy as np
import pandas as pd
array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(array)
print(array.ndim)
print(array.shape)

# conversion to dataframe
df = pd.DataFrame(array, columns = ['A', 'B', 'C'])
df

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2
(3, 3)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

## Section C: Exploring Pandas

In [20]:
# 11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
''''- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows'''

"'- Use .info(), .describe()\n- Select 'Name' and 'City' columns\n- Drop 'City' column\n- Fill any missing values in 'Salary' column with the mean\n- Remove any duplicate rows"

In [21]:
import pandas as pd
data = {
    'Name': ['Raj', 'Vishal', 'Shreya', 'Priya', 'Sagar', 'Anna', 'Vishal', 'Ben', 'Cary', 'John'],
    'Age': [23, 25, 33, 45, 22, 30, 25, 50, 27, 28],
    'City': ['Mumbai', 'Pune', 'Belgaum', 'Bengalore', 'Hydrabad', 'Singapore', 'Pune', 'Shimla', 'America', 'California'],
    'Salary': [25000, 50000, 35000, np.nan, 30000, 60000, 50000, 20000, 30000, 80000]
}

df = pd.DataFrame(data)
df

     Name  Age        City   Salary
0     Raj   23      Mumbai  25000.0
1  Vishal   25        Pune  50000.0
2  Shreya   33     Belgaum  35000.0
3   Priya   45   Bengalore      NaN
4   Sagar   22    Hydrabad  30000.0
5    Anna   30   Singapore  60000.0
6  Vishal   25        Pune  50000.0
7     Ben   50      Shimla  20000.0
8    Cary   27     America  30000.0
9    John   28  California  80000.0

In [22]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [23]:
# decribe
df.describe()

            Age        Salary
count  10.00000      9.000000
mean   30.80000  42222.222222
std     9.44928  19382.838916
min    22.00000  20000.000000
25%    25.00000  30000.000000
50%    27.50000  35000.000000
75%    32.25000  50000.000000
max    50.00000  80000.000000

In [24]:
# Select 'Name' and 'City' columns
df[['Name', 'Age']]

     Name  Age
0     Raj   23
1  Vishal   25
2  Shreya   33
3   Priya   45
4   Sagar   22
5    Anna   30
6  Vishal   25
7     Ben   50
8    Cary   27
9    John   28

In [25]:
# Drop 'City' column

df.drop('City', axis = 1)

     Name  Age   Salary
0     Raj   23  25000.0
1  Vishal   25  50000.0
2  Shreya   33  35000.0
3   Priya   45      NaN
4   Sagar   22  30000.0
5    Anna   30  60000.0
6  Vishal   25  50000.0
7     Ben   50  20000.0
8    Cary   27  30000.0
9    John   28  80000.0

In [26]:
# Check for duplicates

print(df.duplicated().sum())
df.duplicated()

1

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool

In [27]:
# Remove  duplicate row for data of vishal using drop_duplicates
df.drop_duplicates().reset_index()

   index    Name  Age        City   Salary
0      0     Raj   23      Mumbai  25000.0
1      1  Vishal   25        Pune  50000.0
2      2  Shreya   33     Belgaum  35000.0
3      3   Priya   45   Bengalore      NaN
4      4   Sagar   22    Hydrabad  30000.0
5      5    Anna   30   Singapore  60000.0
6      7     Ben   50      Shimla  20000.0
7      8    Cary   27     America  30000.0
8      9    John   28  California  80000.0

In [28]:
# Checking for missing value
df.isnull().sum()

Name      0
Age       0
City      0
Salary    1
dtype: int64

In [29]:
# calculating mean
salary = df['Salary'].mean()
salary

np.float64(42222.22222222222)

In [30]:
# Fill  missing values in 'Salary' column with the mean
df.fillna(salary)

     Name  Age        City        Salary
0     Raj   23      Mumbai  25000.000000
1  Vishal   25        Pune  50000.000000
2  Shreya   33     Belgaum  35000.000000
3   Priya   45   Bengalore  42222.222222
4   Sagar   22    Hydrabad  30000.000000
5    Anna   30   Singapore  60000.000000
6  Vishal   25        Pune  50000.000000
7     Ben   50      Shimla  20000.000000
8    Cary   27     America  30000.000000
9    John   28  California  80000.000000