# BASIC STATISTICS-2

## Hospital Patient Data Analysis

In [63]:
# importing libraries
import pandas as pd
import numpy as np

In [64]:
# Loading the patient dataset 
patient_data = pd.read_csv(r"C:\Users\rasika\Downloads\Patient_Data (1).csv")
df = pd.DataFrame(patient_data)
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [65]:
# Summary of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [66]:
# Droping administrative columns like ['ReceptionistID', 'CheckInTime'].
df.drop(['ReceptionistID', 'CheckInTime'], axis = 1, inplace = True)
df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [67]:
# Use groupby to find total bill amount per department.
df.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [68]:
# Remove duplicate patient records based on PatientID.
df.drop_duplicates(inplace = True)
df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [69]:
# Fill missing BillAmount values with the mean bill amount.
BillAmount = df['BillAmount'].mean()
df.fillna(BillAmount, inplace = True)

In [70]:
Billing_data = pd.read_csv(r"C:\Users\rasika\Downloads\Billing_Data (1).csv")
Billing_data

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [72]:
# Merge the billing dataset with patient dataset on PatientID.
df1 = pd.merge(df, Billing_data, on = 'PatientID', how = 'inner')
df1

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [73]:
# Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
new_patients = pd.DataFrame({
    'PatientID' : [106, 107, 108, 109, 110],
    'Name' : ['Methew', 'John', 'Harry', 'Nickol', 'Nick'],
    'Department' : ['Cardiology', 'Neurology', 'Orthopedics', 'Dermatology', 'Cardiology'],
    'Doctor' : ['Dr.Jonas', 'Dr.Jen', 'Dr.Lee', 'Dr.Kevin', 'Dr.John'],
    'BillAmount' : [6000, 4520, 10000, 7000, 2000],
})

In [74]:
new_patients

   PatientID    Name   Department    Doctor  BillAmount
0        106  Methew   Cardiology  Dr.Jonas        6000
1        107    John    Neurology    Dr.Jen        4520
2        108   Harry  Orthopedics    Dr.Lee       10000
3        109  Nickol  Dermatology  Dr.Kevin        7000
4        110    Nick   Cardiology   Dr.John        2000

In [75]:
current_week = pd.concat([df, new_patients], ignore_index = True)
current_week

   PatientID     Name   Department     Doctor    BillAmount
0        101    Alice   Cardiology  Dr. Smith   5000.000000
1        102      Bob    Neurology   Dr. John   6233.333333
2        103  Charlie  Orthopedics    Dr. Lee   7500.000000
3        104    David   Cardiology  Dr. Smith   6200.000000
4        105      Eva  Dermatology   Dr. Rose   6233.333333
5        106   Methew   Cardiology   Dr.Jonas   6000.000000
6        107     John    Neurology     Dr.Jen   4520.000000
7        108    Harry  Orthopedics     Dr.Lee  10000.000000
8        109   Nickol  Dermatology   Dr.Kevin   7000.000000
9        110     Nick   Cardiology    Dr.John   2000.000000

In [76]:
# Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).# 
new_bills = pd.DataFrame({
    'InsuranceCovered' : [3000, 1500, 4000, 2000, 500],
    'FinalAmount' : [3000, 3020, 6000, 5000, 1500]
})
new_bills

   InsuranceCovered  FinalAmount
0              3000         3000
1              1500         3020
2              4000         6000
3              2000         5000
4               500         1500

In [77]:
updated_info = pd.concat([new_patients,new_bills], axis = 1)
updated_info

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,106,Methew,Cardiology,Dr.Jonas,6000,3000,3000
1,107,John,Neurology,Dr.Jen,4520,1500,3020
2,108,Harry,Orthopedics,Dr.Lee,10000,4000,6000
3,109,Nickol,Dermatology,Dr.Kevin,7000,2000,5000
4,110,Nick,Cardiology,Dr.John,2000,500,1500

In [82]:
pd.concat([df1, updated_info], ignore_index = True)

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000
5,106,Methew,Cardiology,Dr.Jonas,6000.000000,3000,3000
6,107,John,Neurology,Dr.Jen,4520.000000,1500,3020
7,108,Harry,Orthopedics,Dr.Lee,10000.000000,4000,6000
8,109,Nickol,Dermatology,Dr.Kevin,7000.000000,2000,5000
9,110,Nick,Cardiology,Dr.John,2000.000000,500,1500